#! /bin/csh
set echo

set chm = ~crowley/charmm/CURRENT/em64t/exec/em64t/charmm
set sander = sander


$chm -i input/create_nacl_psf.inp | tee charmm_output/OUT.create
$chm -i input/ener.inp | tee charmm_output/OUT.ener

chamber -nocmap -vmd \
     -top    toppar/top_all27_prot_na.rtf \
     -param  toppar/par_all27_prot_na.prm \
     -psf    charmm_output/nacl.psf \
     -crd    pdb/nacl.pdb \
     -p      Amber_output/nacl.prmtop \
     -inpcrd Amber_output/nacl.inpcrd


echo -n "Run sander (y/n): "
set yn = $<
if ( $yn == n ) exit

sander:
$sander -O -o stdout \
       -i input/mdin \
       -p Amber_output/nacl.prmtop \
       -c Amber_output/nacl.inpcrd \
       -r Amber_output/nacl.restrt \
       | tee Amber_output/nacl.out

/bin/rm mdinfo
/bin/mv charmm_gold Amber_output/nacl_amber.frcdump
/bin/mv vmd_prmtop  Amber_output/nacl.vmd_prmtop

