all:
	Run

clean:
	-/bin/rm -f  *~ */*~ \
	   mdcrd	     \
	   mdinfo	     \
	   mdout	     \
	   restrt

allclean:
	-/bin/rm -f  *~ */*~ \
	   Amber_output/*    \
	   mdcrd	     \
	   mdinfo	     \
	   mdout	     \
	   restrt            \
	   dhfr*
