#! /bin/csh 

set name=dhfr

/bin/cp ../../../FF_mk_input_goldstd/charmm_ff/dhfr/output/* .
/bin/cp ../../../FF_mk_input_goldstd/charmm_ff/dhfr/psf/* .
/bin/cp ../../../FF_mk_input_goldstd/charmm_ff/dhfr/pdb/* .
set ff = all27_prot_na
if ( $1 != "" ) then
  echo ff is $1
  set ff = $1
endif 
set top=top_$ff.rtf
set par=par_$ff.prm
! set toppar=../../../toppar
set toppar=.


chamber -cmap  \
    -p Amber_output/$name.prmtop \
    -inpcrd Amber_output/${name}_min.inpcrd \
    -crd ${name}_min.pdb \
    -psf $name.psf \
    -top   $top \
    -param $par

sander:
if ( $?SANDER ) then
   set sander = $SANDER
else 
   set sander = `which sander`
endif

$sander -O -i input/mdin -inf mdinfo \
   -c Amber_output/${name}_min.inpcrd \
   -p Amber_output/${name}.prmtop \
   -o stdout |& tee mdout

    mv charmm_gold Amber_output/${name}_min_amber.frcdmp


chamber -cmap  \
    -p Amber_output/$name.prmtop \
    -inpcrd Amber_output/${name}_600k.inpcrd \
    -crd ${name}_600k.pdb \
    -psf $name.psf \
    -top   ../../../toppar/top_all27_prot_na.rtf \
    -param ../../../toppar/par_all27_prot_na.prm

$sander -O -i input/mdin -inf mdinfo \
   -c Amber_output/${name}_600k.inpcrd \
   -p Amber_output/$name.prmtop \
   -o stdout |& tee mdout

    mv charmm_gold Amber_output/${name}_600k_amber.frcdmp

echo "----------------------------------------------------------------"
echo ""
echo "----------------------------------------------------------------"
../../../ffcompare ${name}_min_chm.frcdmp \
              Amber_output/${name}_min_amber.frcdmp
echo "----------------------------------------------------------------"

echo ""
echo "----------------------------------------------------------------"
../../../ffcompare ${name}_600k_chm.frcdmp \
              Amber_output/${name}_600k_amber.frcdmp
echo "----------------------------------------------------------------"

