all:
	Run

clean:
	-/bin/rm -f  *~ */*~ \
	   mdcrd	    \
	   mdinfo	    \
	   mdout	    \
	   restrt

allclean:
	-/bin/rm -f  *~ */*~ methane* charmm*\
	   Amber_output/* \
	   mdcrd	    \
	   mdinfo	    \
	   mdout	    \
	   restrt
