#! /bin/csh
/bin/rm -f                   \
   ANTECHAMBER_AC.AC         \
   ANTECHAMBER_AC.AC0	     \
   ANTECHAMBER_AM1BCC.AC     \
   ANTECHAMBER_AM1BCC_PRE.AC \
   ANTECHAMBER_BOND_TYPE.AC  \
   ANTECHAMBER_BOND_TYPE.AC0 \
   ATOMTYPE.INF		     \
   divcon.in		     \
   divcon.out		     \
   leap.log \
   mdout mdinfo restrt mdcrd 
/bin/rm -f   *prmtop 
/bin/rm -f   *inpcrd
/bin/rm -f   *.mol2
