clean:
	-/bin/rm -f  *~ */*~ \
	   mdcrd	     \
	   mdinfo	     \
	   mdout	     \
	   restrt
allclean:
	-/bin/rm -f  *~ */*~ \
	   Amber_output/[a-oq-z]*    \
	   mdcrd	     \
	   mdinfo	     \
	   mdout	     \
	   restrt            \
	   ts_*

