#! /bin/csh 

set name=ts_dp_6

/bin/cp ../../../FF_mk_input_goldstd/charmm_ff/cellulose_6_mer/output/* .

chamber -nocmap  \
    -p Amber_output/$name.prmtop \
    -inpcrd Amber_output/${name}_min.inpcrd \
    -crd ${name}_min.pdb \
    -psf $name.psf \
    -top   ../../../toppar/top_all36_carb.rtf \
    -param ../../../toppar/par_all36_carb.prm

sander:
if ( $?SANDER ) then
   set sander = $SANDER
else 
   set sander = `which sander`
endif

$sander -O -i input/mdin -inf Amber_output/mdinfo \
   -c Amber_output/${name}_min.inpcrd \
   -p Amber_output/${name}.prmtop \
   -o Amber_output/stdout |& tee mdout

    mv charmm_gold Amber_output/${name}_min_amber.frcdmp


chamber -nocmap  \
    -p Amber_output/$name.prmtop \
    -inpcrd Amber_output/${name}_600k.inpcrd \
    -crd ${name}_600k.pdb \
    -psf $name.psf \
    -top   ../../../toppar/top_all36_carb.rtf \
    -param ../../../toppar/par_all36_carb.prm

$sander -O -i input/mdin -inf Amber_output/mdinfo \
   -c Amber_output/${name}_600k.inpcrd \
   -p Amber_output/$name.prmtop \
   -o Amber_output/stdout |& tee mdout

    mv charmm_gold Amber_output/${name}_600k_amber.frcdmp

echo "----------------------------------------------------------------"
echo ""
echo "----------------------------------------------------------------"
../../../ffcompare ${name}_min_chm.frcdmp \
              Amber_output/${name}_min_amber.frcdmp
echo "----------------------------------------------------------------"

echo ""
echo "----------------------------------------------------------------"
../../../ffcompare ${name}_600k_chm.frcdmp \
              Amber_output/${name}_600k_amber.frcdmp
echo "----------------------------------------------------------------"

