#! /bin/csh -x

set runit
set chm = charmm
if $1 == "M" then
  set runit  = "mpirun -np $2"
  set chm = mcharmm
  shift;shift
endif
echo $runit

set name=dhfr_vac
set toppar=../../../toppar

set ff = all36_prot
if ( $1 != "" ) then
  echo ff is $1
  set ff = $1
endif 
set top=top_$ff.rtf
set par=par_$ff.prm

$runit $chm -i  input/$name.inp ff=$ff | tee charmm_output/charmm.out

chamber -cmap  \
    -p Amber_output/$name.prmtop \
    -inpcrd Amber_output/$name.inpcrd \
    -crd pdb/$name.pdb \
    -psf psf/$name.psf \
    -top   $toppar/$top \
    -param $toppar/$par


echo -n "Run sander (y/n): "
set yn = $<
if ( $yn == n ) exit

sander:
if ( $?SANDER ) then
   set sander = $SANDER
else 
   set sander = `which sander`
endif

$sander -O -i input/mdin -inf Amber_output/mdinfo \
   -c Amber_output/$name.inpcrd \
   -p Amber_output/$name.prmtop \
   -o Amber_output/stdout |& tee mdout

    mv charmm_gold Amber_output/${name}_amber.frcdmp


chamber -cmap  \
    -p Amber_output/$name.prmtop \
    -inpcrd Amber_output/${name}_600k.inpcrd \
    -crd pdb/${name}_600k.pdb \
    -psf psf/$name.psf \
    -top   $toppar/$top \
    -param $toppar/$par

$sander -O -i input/mdin -inf Amber_output/mdinfo \
   -c Amber_output/${name}_600k.inpcrd \
   -p Amber_output/$name.prmtop \
   -o Amber_output/stdout |& tee mdout

    mv charmm_gold Amber_output/${name}_600k_amber.frcdmp

echo "----------------------------------------------------------------"
echo ""
echo "----------------------------------------------------------------"
../ffcompare charmm_output/${name}_chm.frcdmp \
              Amber_output/${name}_amber.frcdmp
echo "----------------------------------------------------------------"

echo ""
echo "----------------------------------------------------------------"
../ffcompare charmm_output/${name}_600k_chm.frcdmp \
              Amber_output/${name}_600k_amber.frcdmp
echo "----------------------------------------------------------------"

