#! /bin/csh
/bin/cp ../../../FF_mk_input_goldstd/charmm_ff/nacl/output/* .
if ( ! -d Amber_output ) mkdir Amber_output

chamber -nocmap \
     -top    ../../../toppar/top_all27_prot_na.rtf \
     -param  ../../../toppar/par_all27_prot_na.prm \
     -psf    nacl.psf \
     -crd    nacl.pdb \
     -p      Amber_output/nacl.prmtop \
     -inpcrd Amber_output/nacl.inpcrd


sander -O -o stdout \
       -i input/mdin \
       -p Amber_output/nacl.prmtop \
       -c Amber_output/nacl.inpcrd \
       -r nacl.restrt \
       | tee Amber_output/nacl.out

/bin/rm mdinfo
/bin/mv charmm_gold Amber_output/nacl_amber.frcdmp
/bin/mv vmd_prmtop  Amber_output/nacl.vmd_prmtop

echo "----------------------------------------------------------------"
echo ""
echo "----------------------------------------------------------------"
../../../ffcompare Amber_output/nacl_amber.frcdmp nacl_chm.frcdmp

echo "----------------------------------------------------------------"
